export default {
  // Services
  MAIL_SERVICE: "MAIL_SERVICE",
  MAIL_SERVICE_NAME: "MAIL_SERVICE_V1",

  BOOKING_SERVICE: "BOOKING-SERVICE",
  BOOKING_SERVICE_NAME: "BOOKING-SERVICE_V1",

  AUTH_SERVICE: "AUTH-SERVER",
  AUTH_SERVICE_NAME: "AUTH-SERVER_V1",
};
