export default {
  // Services
  REVIEW_SERVICE: "REVIEW-SERVICE",
  REVIEW_SERVICE_NAME: "REVIEW-SERVICE_V1",

  ROOM_SERVICE: "ROOM-SERVICE",
  ROOM_SERVICE_NAME: "ROOM-SERVICE_V1",

  ORGANIZATION_SERVICE: "ORGANIZATION-SERVICE",
  ORGANIZATION_SERVICE_NAME: "ORGANIZATION-SERVICE_V1",
};
