export default {
  // API constants
  SCHEME: "https",
  HOSTNAME: "myroom.com",
  VERSION: "v1",

  // API URI
  ORGANIZATION_SERVICE_API_V1: "/api/v1/organization-service",

  // API error code
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_DATA: "INVALID_DATA",
  DUPLICATE_KEY: "DUPLICATE_KEY",
  INVALID_ORGANIZATION_ID: "INVALID_ORGANIZATION_ID",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // API error message
  MESSAGE_INTERNAL_SERVER_ERROR: "Internal Server Error",
  MESSAGE_BAD_REQUEST: "Bad Request",
  MESSAGE_NOT_FOUND: "Not Found",
  MESSAGE_SUCCESS: "Success",
  MESSAGE_INVALID_ROOM_ID: "Invalid roomId",

  // API error description
  DESCRIPTION_INTERNAL_SERVER_ERROR: "Something went wrong!",
};
